# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16fxs0o0mvRjqxMGm6Dz02_abYB_w0sv5
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import time

from google.colab import files
files.upload()

# 2. X (Özellikler) ve y (Hedef) Olarak Ayırma
df = pd.read_csv('İnsan Aktivitesi Tanıma (UCI HAR).csv')
X = df.drop(columns=['Activity', 'subject'])
y = df['Activity']

# 3. Veriyi Ölçeklendirme (Standardizasyon)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 4. Boyut İndirgeme (PCA)
# Bilginin (varyansın) %95'ini koruyacak şekilde ayarlıyoruz.
pca = PCA(n_components=0.95)
X_pca = pca.fit_transform(X_scaled)
print(f"Orijinal Öznitelik Sayısı: {X_scaled.shape[1]}")
print(f"PCA Sonrası Öznitelik Sayısı: {X_pca.shape[1]}")

# 5. Eğitim ve Test Setlerine Ayırma
X_train_orig, X_test_orig, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
X_train_pca, X_test_pca, _, _ = train_test_split(X_pca, y, test_size=0.2, random_state=42)

# 6. Model Eğitimi
rf_model = RandomForestClassifier(random_state=42)

# --- Orijinal Veri ile Test ---
start_time = time.time()
rf_model.fit(X_train_orig, y_train)
y_pred_orig = rf_model.predict(X_test_orig)
acc_orig = accuracy_score(y_test, y_pred_orig)
time_orig = time.time() - start_time

# --- PCA Verisi ile Test ---
start_time = time.time()
rf_model.fit(X_train_pca, y_train)
y_pred_pca = rf_model.predict(X_test_pca)
acc_pca = accuracy_score(y_test, y_pred_pca)
time_pca = time.time() - start_time

# 7. Performans Karşılaştırması
print("\n--- Orijinal Veri Performansı ---")
print(f"Doğruluk (Accuracy): %{acc_orig*100:.2f}")
print(f"Eğitim ve Tahmin Süresi: {time_orig:.2f} saniye")

print("\n--- PCA Verisi Performansı ---")
print(f"Doğruluk (Accuracy): %{acc_pca*100:.2f}")
print(f"Eğitim ve Tahmin Süresi: {time_pca:.2f} saniye")

import pickle

# Modeli, Scaler'ı ve PCA objesini diske kaydetme
with open('rf_model.pkl', 'wb') as f:
    pickle.dump(rf_model, f)

with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

with open('pca.pkl', 'wb') as f:
    pickle.dump(pca, f)

!pip install streamlit
import streamlit as st
import pandas as pd
import pickle

# Sayfa Başlığı
st.title("İnsan Aktivitesi Tanıma Uygulaması 🏃‍♂️🚶‍♀️")
st.write("Akıllı telefon sensör verilerini kullanarak kullanıcının hangi aktiviteyi yaptığını tahmin eden makine öğrenmesi modeli.")

# 1. Eğitilmiş Modelleri ve Dönüştürücüleri Yükleme
@st.cache_resource
def load_models():
    with open('rf_model.pkl', 'rb') as f:
        model = pickle.load(f)
    with open('scaler.pkl', 'rb') as f:
        scaler = pickle.load(f)
    with open('pca.pkl', 'rb') as f:
        pca = pickle.load(f)
    return model, scaler, pca

model, scaler, pca = load_models()

# 2. Veri Setini Yükleme (Arka plandan rastgele veri çekmek için)
@st.cache_data
def load_data():
    # Jupyter dosyasındaki CSV adını kullandık
    df = pd.read_csv('İnsan Aktivitesi Tanıma (UCI HAR).csv')
    X = df.drop(columns=['Activity', 'subject'])
    y = df['Activity']
    return X, y

X, y = load_data()

st.write("---")

# 3. Buton ve Tahmin İşlemi
if st.button("Sensörden Rastgele Veri Al ve Tahmin Et 🎲"):
    # Veri setinden rastgele 1 satır (1 anlık sensör ölçümü) çekiyoruz
    random_index = X.sample(1).index[0]
    sample_data = X.loc[[random_index]]
    actual_activity = y.loc[random_index]

# 3. Buton ve Tahmin İşlemi
if st.button("Sensörden Rastgele Veri Al ve Tahmin Et 🎲"):
    # Veri setinden rastgele 1 satır (1 anlık sensör ölçümü) çekiyoruz
    random_index = X.sample(1).index[0]
    sample_data = X.loc[[random_index]]
    actual_activity = y.loc[random_index]

    # Seçilen veriyi önce standartlaştırıp (Scaler) sonra boyutunu düşürüyoruz (PCA)
    sample_scaled = scaler.transform(sample_data)
    sample_pca = pca.transform(sample_scaled)

    # Eğitilmiş Random Forest modelimizle tahmin yapıyoruz
    prediction = model.predict(sample_pca)[0]

    # Sonuçları ekrana yazdırıyoruz
    st.subheader("Sonuçlar:")
    st.write(f"**Gerçekte Yapılan Aktivite:** {actual_activity}")
    st.write(f"**Yapay Zekanın Tahmini:** {prediction}")

    if actual_activity == prediction:
        st.success("Tebrikler! Model doğru tahmin etti. 🎉")
    else:
        st.error("Model bu sefer yanıldı. 😔")